CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(200) NOT NULL,
    accepted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE sessions (
    id VARCHAR2(50) PRIMARY KEY,
    user_id NUMBER NOT NULL,
    ip VARCHAR2(45) NOT NULL,
    connection_time TIMESTAMP NOT NULL,
    disconnection_time TIMESTAMP NULL,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id NUMBER NOT NULL,
    receiver_id NUMBER NOT NULL,
    content_type VARCHAR2(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_msg_receiver FOREIGN KEY (receiver_id) REFERENCES users(id)
);

CREATE TABLE message_receivers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    session_id VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_msgrec_msg FOREIGN KEY (message_id) REFERENCES messages(id),
    CONSTRAINT fk_msgrec_ses FOREIGN KEY (session_id) REFERENCES sessions(id)
);

CREATE TABLE text_contents (
    message_id NUMBER PRIMARY KEY,
    text CLOB NOT NULL,
    CONSTRAINT fk_txt_msg FOREIGN KEY (message_id) REFERENCES messages(id)
);

CREATE TABLE file_contents (
    message_id NUMBER PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    size NUMBER NOT NULL,
    data BLOB NOT NULL,
    CONSTRAINT fk_file_msg FOREIGN KEY (message_id) REFERENCES messages(id)
);
