package com.proyect.GUI;

import com.proyect.DTO.UserDTO;
import com.proyect.controller.ServerController;
import com.proyect.controller.UserController;
import com.proyect.domain.interfaces.IObserver;
import com.proyect.factory.ExternalFactory;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class VentanaPrincipal extends javax.swing.JFrame implements IObserver {

    private VentanaPrincipal() {
        pends = new ArrayList<>();
        modelPends = new DefaultListModel<>();
        initComponents();
        serverController = ExternalFactory.getServerController();
        userController = ExternalFactory.getUserController();

        loadPends();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNIniciarServidor = new javax.swing.JButton();
        BTNDetenerServidor = new javax.swing.JButton();
        ScrollPaneConectados = new javax.swing.JScrollPane();
        ListUsersConected = new javax.swing.JList<>();
        ScrollPanePendientes = new javax.swing.JScrollPane();
        ListPendientes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SERVIDOR");

        BTNIniciarServidor.setText("Iniciar Servidor");
        BTNIniciarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIniciarServidorActionPerformed(evt);
            }
        });

        BTNDetenerServidor.setText("Detener Servidor");
        BTNDetenerServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDetenerServidorActionPerformed(evt);
            }
        });

        ListUsersConected.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScrollPaneConectados.setViewportView(ListUsersConected);

        ListPendientes.setModel(modelPends);
        ScrollPanePendientes.setViewportView(ListPendientes);

        jLabel2.setText("Usuarios no aceptados");

        jLabel3.setText("Usuarios conectados");

        jButton1.setText("Aceptar usuarios seleccionados");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollPaneConectados)
                            .addComponent(ScrollPanePendientes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNIniciarServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNDetenerServidor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNIniciarServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNDetenerServidor)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollPanePendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNIniciarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIniciarServidorActionPerformed
        serverController.start();
    }//GEN-LAST:event_BTNIniciarServidorActionPerformed

    private void BTNDetenerServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDetenerServidorActionPerformed
        serverController.stop();
    }//GEN-LAST:event_BTNDetenerServidorActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        List<UserDTO> usersAccepted = ListPendientes.getSelectedValuesList();
        if(!usersAccepted.isEmpty()){
            for(UserDTO userDTO : usersAccepted){
                userController.approveUser(userDTO.getId());
                modelPends.removeElement(userDTO);
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDetenerServidor;
    private javax.swing.JButton BTNIniciarServidor;
    private javax.swing.JList<UserDTO> ListPendientes;
    private javax.swing.JList<String> ListUsersConected;
    private javax.swing.JScrollPane ScrollPaneConectados;
    private javax.swing.JScrollPane ScrollPanePendientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    private ServerController serverController;
    private static VentanaPrincipal instance;
    private UserController userController;
    private List<UserDTO> pends;
    private DefaultListModel<UserDTO> modelPends;

    public static VentanaPrincipal getInstance() {
        if (instance == null) {
            instance = new VentanaPrincipal();
        }
        return instance;
    }

    @Override
    public void update(String update) {

    }

    private void loadPends() {
        pends = userController.getNonAcceptedUsers();
        if (pends.size() > 0) {
            modelPends.clear();
            for (UserDTO userDTO : pends) {
                modelPends.addElement(userDTO);
            }
        }
    }
}
